spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:checklist_db}
spring.datasource.username=${DB_USER:checklist_user}
spring.datasource.password=${DB_PASSWORD:checklist_password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


checklist.security.swagger-public=true
checklist.security.jwt.secret=${JWT_SECRET}
spring.jpa.defer-datasource-initialization=true

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema-postgresql.sql

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.virtual-host=/

app.rabbitmq.exchange=notifications.exchange
app.rabbitmq.queue=notifications.dispatch.q
app.rabbitmq.dlq=notifications.dispatch.dlq
app.rabbitmq.routing-key=checklist.non_compliance.created