spring:
  application:
    name: conecta.checklist
  profiles:
    default: local

server:
  port: ${SERVER_PORT:8083}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

checklist:
  security:
    swagger-public: false
    jwt:
      secret: ${JWT_SECRET}
  timezone: America/Sao_Paulo

hub:
  api:
    url: ${HUB_API_URL}
