spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      schema-locations: classpath:schema-postgresql.sql

checklist:
  security:
    swagger-public: true

logging:
  level:
    root: INFO
    com.portal.conecta: DEBUG
management:
  endpoint:
    health:
      show-details: always
