spring.autoconfigure.exclude=org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration,org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration

spring.jpa.show-sql=false
spring.sql.init.mode=never

checklist.security.swagger-public=true
checklist.security.jwt.secret=MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=
hub.api.url=http://localhost:8081
