spring.application.name=conecta.checklist
spring.profiles.default=local

server.port=${SERVER_PORT:8080}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when_authorized

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

checklist.security.jwt.secret=${JWT_SECRET:default-secret-key-that-is-at-least-256-bits-long-for-hmac-sha-256-portal-conecta-checklist-api}
