spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: false
  h2:
    console:
      enabled: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

checklist:
  security:
    swagger-public: true

app:
  rabbitmq:
    enabled: false

logging:
  level:
    root: WARN
    com.portal.conecta: DEBUG
